[staging]

# US boxes
100.123.214.111 ansible_user=ubuntu region=us-west public_ip=131.153.225.113 accepted_cpus=32
100.98.87.115 ansible_user=ubuntu region=us-west public_ip=125.253.85.93
100.117.246.26 ansible_user=ubuntu region=us-west public_ip=131.153.240.135
100.66.50.42 ansible_user=ubuntu region=us-west public_ip=125.253.73.241
100.111.226.121 ansible_user=ubuntu region=us-west public_ip=125.253.73.183
100.114.222.40 ansible_user=ubuntu region=us-west public_ip=131.153.142.243

# EU boxes
# 100.108.157.124 ansible_user=root region=eu-central public_ip=157.90.219.177
100.66.145.57 ansible_user=root region=eu-central public_ip=168.119.192.58
100.64.50.21 ansible_user=root region=eu-central public_ip=168.119.192.56

# EU ARM boxes
100.102.107.93 ansible_user=root region=eu-central public_ip=46.4.211.7

# US ARM boxes
100.75.15.120 ansible_user=ubuntu region=us-west public_ip=125.253.86.237
100.103.91.38 ansible_user=ubuntu region=us-west public_ip=125.253.86.185

[staging:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

